language:
    - php
    - node_js

php:
    - 5.3
    - 5.4

node_js:
    - 0.10

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=0

before_script:
    - if [ -z "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - $DEV_LIB_PATH/travis.before_script.sh

script:
    - $DEV_LIB_PATH/travis.script.sh

after_script:
    - $DEV_LIB_PATH/travis.after_script.sh
